### ISSUE TITLE
Print rock version in preamble

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/rock#50]
Now when compiling with rock it prints this preamble:
> magic-lang rock compiler

could be nice to have a version number there too
> magic-lang rock compiler (1.0.19-head)

@thomasfanell

**Comment by thomasfanell** [comment]
I agree, I was thinking the same yesterday while looking over PRint logs. @fredrikbryntesson what do you say?

**Comment by marcusnaslund** [comment]
Does this mean I get to see "Kapten Freppalicious" every time I compile?

**Comment by fredrikbryntesson** [comment]
Sure, if it makes  you happy.

**Comment by thomasfanell** [comment]
@marcusnaslund it could happen
