### ISSUE TITLE
Adding enum elements to a List

### ISSUE THREAD

**Issue by naslundx** [magic-lang/rock#67]
The following code fails
```ooc
use math

list := IntVectorList new()
list add(Owner Receiver as Int)
list[0] toString() println()
```
with `error: lvalue required as unary ‘&’ operand`.

The following code works
```ooc
use math

list := IntVectorList new()
list add(_ := Owner Receiver as Int)
list[0] toString() println()
```
clearly, the values from the enum have to be assigned to *something* before added to a list. I think rock should be able to figure this out automatically.

I can't atm test if the same is true of `ArrayList` and ooc-lang/rock (hence the issue here) but I would guess so.

**Comment by marcusnaslund** [comment]
Accidentally used the wrong github account. Ah well.

**Comment by shamanas** [comment]
This looks like it could have been fixed by #45, checking...

**Comment by thomasfanell** [comment]
This appears to be fixed now. Closing

**Comment by marcusnaslund** [comment]
Awesome. :+1:
