### ISSUE TITLE
Can we export unmangled global variables ?

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/rock#76]
I would like to do something like
```C
// file.c
const int MY_VAR = -1;

// file.h
extern const int MY_VAR;
```

Where in .ooc file should I place the definition of `MY_VAR: unmangled Int = -1` ? Placing it in the global scope seems to generate only a local variable in the module's `load` function:
```ooc
// file.ooc
MY_VAR: unmangled Int = -1

// --> file.c
void file_something_load() {
    ...
    Numbers__Int MY_VAR = -1; // only a local variable !
    ...
}
```
I guess I could add a plain .c file with just the variable definition (or use unmangled function to return the value), but it seems like easy enough task to be solved via "pure" ooc. And I'm also curious if / how it's possible.

**Comment by thomasfanell** [comment]
That is weird, since when I try that (placing it in global scope), I get this:

*file.c*
```
Numbers__Int MY_VAR;
```
*file-fwd.h*
```
extern Numbers__Int MY_VAR;
```

and then in `file_load()`
```
MY_VAR = -1;
```

**Comment by sebastianbaginski** [comment]
Thanks, I will try that again on the same files I tried before and let you know.

**Comment by thomasfanell** [comment]
Created a specific issue for variables defined inside a version block. #77
