### ISSUE TITLE
Is operator `as` unreliable when testing for inheritance ?

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/rock#79]
```ooc
use base

Base: abstract class {
	init: func
	doit: abstract func
}

GoodClass: class extends Base {
	init: func
	doit: override func { "good" println() }
}

BadClass: class extends Base {
	init: func
	doit: override func { "VERY BAD" println() }
}

instance: Base
instance = BadClass new()
if (instance as GoodClass)
	instance doit()

```

output:

> VERY BAD

Is it unsafe to use `operator as` to test for a `is a kind of` - type of relation ? I would expect `instance as GoodClass` to fail because `instance` is an object of the `BadClass`.
Do I have an error somewhere in my code (or are my assumptions about the "as" operator incorrect) ?
@thomasfanell

**Comment by thomasfanell** [comment]
`as` is not intended to be used this way I don't think, so no, I would not trust it. I would instead use
```
if (instance instanceOf(GoodClass))
	instance doit()
```

**Comment by sebastianbaginski** [comment]
OK, thanks. Sometimes in our "main" code base we use `as` without checking for `instanceOf` before that. But I guess we can close this one.

**Comment by marcusnaslund** [comment]
Indeed, `as` is used for casting to another type, not for checking current type. I think you may cast any class to any class and it won't fail until you try to use it the wrong way.

**Comment by shamanas** [comment]
Just to be clear, if you are familiar with C++ terms, `as` is a static cast (C cast), not a dynamic cast (it does not return null if the object you are casting is not of the type you are casting to).  

You could probably overload it to have this behavior though, something like:  
```ooc
operator <T> as (obj: Object) -> T {
    if (obj instanceOf(T)) {
        obj as T
    } else {
        null
    }
}

```

would probably work although I'm not quite sure

**Comment by shamanas** [comment]
Also, much cleaner than using instanceOf:  
```ooc
match obj {
    case entity: Entity => doStuff(entity)
}
```  
(Although it can be cumbersome if you only need to test for one type)

**Comment by sebastianbaginski** [comment]
Yeah I don't know why but I was under the impression that your "overloaded" implementation was the default in ooc for Objects :/
